spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 323844336043-sq12ktiublpb5dq6kb19cenhlpg28dsr.apps.googleusercontent.com
            client-secret: UEmLIiXCFMrwhn4OWoKvbTiN
          facebook:
            client-id: 1927214790702719
            client-secret: af47d69a3b226b188d5d89614dc55689
custom:
  oauth2:
    kakao:
      client-id: 910c0796e5b1f8b613c28bd91be7d382