spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: false
    path: /console
  devtools:
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 323844336043-sq12ktiublpb5dq6kb19cenhlpg28dsr.apps.googleusercontent.com
            client-secret: UEmLIiXCFMrwhn4OWoKvbTiN
          facebook:
            client-id: 1927214790702719
            client-secret: af47d69a3b226b188d5d89614dc55689
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
custom:
  oauth2:
    kakao:
      client-id: d546778ec26ccf4e0fcf2e453c0f5915
